accounts/urls.py
from django.urls import path
from . import views
from accounts.views import AccountChartView



urlpatterns = [
    path('', views.home, name='home'),
    path('stores/', views.stores, name='stores'),
    path('reports/', views.reports, name='reports'),
    path('announcements/', views.announcements, name='announcements'),
    path('restricted/', views.accessRestricted, name="restricted"),

    #email with file
    path('send_email/', views.EmailAttachementView, name='send_email'),
    # path('statistics_page/', views.statistics_page, name='statistics_page'),
    
    path('login/', views.loginPage, name='login'),
    path('register/admin/', views.registerAdminPage, name='registeradmin'),
    path('register/tenant/', views.registerTenantPage, name='registertenant'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name='logout'),

    # forms
    path('createNonFBReport_form/', views.createNonFBReport, name='createNonFBReport_form'),
    path('createFBReport_form/', views.createFBReport, name='createFBReport_form'),
    path('createCovidReport_form/', views.createCovidReport, name='createCovidReport_form'),
    path('rectify_form/', views.createRectification, name='rectify_form'),

    # charts
    path('chart/', AccountChartView.as_view(), name='chart'),

    # test (delete later)
    path('testAccess/', views.testAccess, name='testAccess'),
]

crm1/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
# from emailattachment import urls as emailattachment_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    # path('', include(emailattachment_urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class NonFBChecklist(models.Model):
    checklist_item = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    # not sure if we actually need this, can remove later
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.checklist_item


class CovidComplianceChecklist(models.Model):
    measures_item = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    # not sure if we actually need this, can remove later
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.measures_item


class FBChecklist(models.Model):
    item = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    # not sure if we actually need this, can remove later
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.item

# used as template for Create Report form


class Store(models.Model):
    CATEGORY = (
        ('FB', 'FB'),
        ('Non-FB', 'Non-FB')
    )

    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    rectificationNeeded = models.BooleanField(null=True)
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    description = models.CharField(max_length=200, null=True, blank=True)
    # to be calculated
    score = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    audit_date = models.DateField("dd/mm/yyyy", auto_now_add=False, null=True)
    # not sure if we actually need this, can remove later
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.name


class NonFBReport(models.Model):
    store = models.ForeignKey(Store, null=True, on_delete=models.SET_NULL)
    report_number = models.IntegerField()
    compliance = models.ManyToManyField(NonFBChecklist)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    score = models.IntegerField()

    def __str__(self):
        return str(self.report_number)  # give name in the admin panel


class FBReport(models.Model):
    store = models.ForeignKey(Store, null=True, on_delete=models.SET_NULL)
    report_number = models.IntegerField()
    compliance = models.ManyToManyField(FBChecklist)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    score = models.IntegerField()

    def __str__(self):
        return str(self.report_number)  # give name in the admin panel


class CovidReport(models.Model):
    store = models.ForeignKey(Store, null=True, on_delete=models.SET_NULL)
    report_number = models.IntegerField()
    compliance = models.ManyToManyField(CovidComplianceChecklist)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    score = models.IntegerField()

    def __str__(self):
        return str(self.report_number)  # give name in the admin panel

# TODO: rename to Rectify


class Order(models.Model):
    STATUS = (
        ('Notification Sent', 'Notification Sent'),
        ('Pending', 'Pending'),
        ('Completed', 'Completed'),
    )

    store = models.ForeignKey(Store, null=True, on_delete=models.SET_NULL)
    Non_FB_Report = models.ForeignKey(
        NonFBReport, null=True, on_delete=models.SET_NULL)
    FB_Report = models.ForeignKey(
        FBReport, null=True, on_delete=models.SET_NULL)
    Covid_Compliance_Report = models.ForeignKey(
        CovidReport, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    issue = models.ForeignKey(
        NonFBChecklist, null=True, on_delete=models.SET_NULL)
    # if (store.Store):
    #     issue = models.ForeignKey(NonFBChecklist, null=True, on_delete=models.SET_NULL)
    # else:
    #     issue = models.ForeignKey(FBChecklist, null=True, on_delete=models.SET_NULL)
    covid_compliance = models.ForeignKey(
        CovidComplianceChecklist, null=True, on_delete=models.SET_NULL)

    upload_image = models.FileField(upload_to='uploads/')

    def __str__(self):
        return self.store.name


class Announcement(models.Model):
    announcement_title = models.CharField(max_length=200, null=True)
    announcement_text = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.announcement_title


class AuditScore(models.Model):
    name = models.CharField(max_length=30)
    score = models.FloatField()

    def __str__(self):
        return "{}: {}".format(self.name, self.score)


class Send_email(models.Model):
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.email


class Statistics_page(models.Model):
    statistics_name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.statistics_name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Order, NonFBReport, FBReport, CovidReport, NonFBChecklist, CovidComplianceChecklist, FBChecklist


class RectifyForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['store', 'Non_FB_Report', 'FB_Report',
                  'Covid_Compliance_Report', 'upload_image']


class EmailForm(forms.Form):
    email = forms.EmailField()
    subject = forms.CharField(max_length=100)
    attach = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}))
    message = forms.CharField(widget=forms.Textarea)


class CreateNonFBReportForm(forms.ModelForm):
    class Meta:
        model = NonFBReport
        fields = ['store', 'report_number', 'compliance', 'score']

    def __init__(self, *args, **kwargs):
        super(CreateNonFBReportForm, self).__init__(*args, **kwargs)
        self.fields['compliance'].widget = forms.CheckboxSelectMultiple()
        self.fields['compliance'].queryset = NonFBChecklist.objects.all()


class CreateFBReportForm(forms.ModelForm):
    class Meta:
        model = FBReport
        fields = ['store', 'report_number', 'compliance', 'score']

    def __init__(self, *args, **kwargs):
        super(CreateFBReportForm, self).__init__(*args, **kwargs)
        self.fields['compliance'].widget = forms.CheckboxSelectMultiple()
        self.fields['compliance'].queryset = FBChecklist.objects.all()


class CreateCovidReportForm(forms.ModelForm):
    class Meta:
        model = CovidReport
        fields = ['store', 'report_number', 'compliance', 'score']

    def __init__(self, *args, **kwargs):
        super(CreateCovidReportForm, self).__init__(*args, **kwargs)
        self.fields['compliance'].widget = forms.CheckboxSelectMultiple()
        self.fields['compliance'].queryset = CovidComplianceChecklist.objects.all()


class CreateUserForm(UserCreationForm):
    def clean(self):
        cleaned_data = super(CreateUserForm, self).clean()

        username = cleaned_data.get('username')
        if username and User.objects.filter(username__iexact=username).exists():
            self.add_error(
                'username', 'A user with that username already exists.')

        email = cleaned_data.get('email')
        if email and User.objects.filter(email__iexact=email).exists():
            self.add_error(
                'email', 'A user with that email already exists.')

        return cleaned_data

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

accounts/templates/accounts/announcements.html
{% extends 'accounts/main.html' %}

{% block title %} - Announcements{% endblock title %}

{% block content %}
    <br>

        <div class="row">
            <div class="col-md">
                <div class="card card-body">
                    <h5>Announcements</h5>
                </div>
                <div class="card card-body">
                <table class="table table-sm">
                        <tr>
                         <th style="width: 20%;">Date Created</th>
                         <th style="width: 15%;">Title</th>
                         <th style="width: 65%;">Announcement</th>
                        </tr>
            
                    {% for announcement in announcements %}
                        <tr>
                        <td>{{announcement.date_created}}</td>
                        <td>{{announcement.announcement_title}}</td>
                        <td>{{announcement.announcement_text}}</td>
                        </tr>
                    {% endfor %}

                    </table>
                </div>
            </div>

        </div>

{% endblock %}

accounts/templates/accounts/chart.html
{% extends 'accounts/main.html' %}

{% block title %} - Accounts Ranking{% endblock title %}

{% block scripts %}
<script>
$(document).ready(function(){
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [{% for item in qs %}'{{item.name}}',{% endfor %}],
            datasets: [{
                label: 'Audit scores of tenants',
                data: [{% for item in qs %}'{{item.score}}',{% endfor %}],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
})

</script>
{% endblock scripts %}

{% block content %}
    <canvas id="myChart" width="400" height="200"></canvas>
{% endblock content %}

accounts/templates/accounts/createReport_form.html
{% extends 'accounts/main.html' %}
{% load static %}

{% block title %} - Create Report{% endblock title %}

{% block cssblock %}
<style>
    #id_compliance li{
        list-style-type: none;
        margin-bottom: 20px;
    }
    #id_compliance{
        padding-left: 5%;
    }
    input{
        margin-right: 10px!important;
    }
    label {
        margin-right: 15px;
    }
</style>
{% endblock cssblock %}

{% block content %}
<div style="margin: 0 5%;">
    <div>
        <div style="margin: 20px 0px; color: #0069D9">
            <h1>{{ pageTitle }}</h1>
        </div>
    </div>
    <div style="padding-left: 10px;">
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" name="submit">

        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/footer.html
{% load static %}

<!-- Footer -->
<footer class="bg-light text-center text-lg-start bg" style="margin-top: 25vh;">

    <!-- Grid container -->
    <div class="container p-4">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-6 col-md-12 mb-4 mb-md-0" style="padding-bottom: 20px;">
          <h5 class="text-uppercase">SingHealth's Purpose</h5>
  
          <p>
            We are united by our common purpose to put ‘Patients. At the Heart of All We Do.’  Our institutions may span from primary to acute care but the fundamental principle to place patients at the heart of all initiatives remains. We aim to ensure that they remain well-supported as they journey from one care setting to another.
          </p>
        </div>
        <!--Grid column-->
  
        <!--Grid column-->
        <div class="col-lg-2 col-md-0 mb-4 mb-md-0">
          
        </div>
        <!--Grid column-->
  
        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-0" style="padding-bottom: 10px;;">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a class="nav-link" href="{% url 'announcements' %}" class="text-dark">Contact Us</a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'announcements' %}" class="text-dark">Announcements</a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'stores' %}" class="text-dark">Directory</a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'announcements' %}" class="text-dark">Help Desk Support</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Grid container -->
    <img src="{% static 'images/SingHealth_WebApp_footer_image.png' %}" width="1020" style="margin-right: 10px;">

  </footer>
  <!-- Footer -->

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
    
<head>
    <title>{% include 'accounts/webappName.html' %} - Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<meta content="width=device-width, initial-scale=1" name="viewport" />

    <style>
        body{
            background-color: #FFF9E3;    
        }
        
        .user_card {
			width: 100%;;
			margin: auto;
			padding: 20px 10px 25px;
			background: #FADC74;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}


		.form_container {
			margin-top: 10px;
		}

		#form-title{
			color: #000000;
			
		}

		.login_btn {
			width: 100%;
			background: #F6C27E  !important;
			color: black  !important;
			margin-top: 10px;
			font-weight: bold;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_btn:hover {
			background: #F4B086!important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #F6C27E  !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
        
        .circle {
            border-radius: 100%;
            position: fixed;
        }

        #left {
            height: 120vh;
            width: 75vw;
            background-color: #FCE7A0;
            left: -75vh;
            bottom: -40vw;
        }

		#right {
            height: 50vh;
            width: 35vw;
            background-color: #F9CEAD;
            right: -35vh;
            top: -15vw;
        }

		
		h3 {
			font-family: Tahoma, sans-serif;
		}
		
    </style>

</head>

<body>
    <div class="container" style="height: 100vh; width: 100vw;">
        <div class="row w-100" style="margin: 0;">
            <div class="col-md-3"></div>
            <div class=" col-md-6">
                <div class="container flex-column mx-auto" style="padding-top: 14vh;">
                    <div class="header mx-auto text-center">
                        <h1>{% include 'accounts/webappName.html' %}</h1>
                    </div>

                    <div class="user_card" style="margin-top: 5vh;">
                        <div class="d-flex justify-content-center">
                            <h3 id="form-title">Login</h3>
                        </div>
                        <div class="d-flex justify-content-center form_container">
                            <form method="POST" action="">
                                {% csrf_token %}
                                <div class="input-group mb-3">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                                    </div>

                                    <input type="text" name="username" placeholder="Username..." class="form-control">
                                </div>

                                <div class="input-group mb-2">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                                    </div>

                                    <input type="password" name="password" placeholder="Password..." class="form-control">
                                </div>

                                <div class="d-flex justify-content-center mt-3 login_container">
                                    <input class="btn login_btn" type="submit" value="Login">
                                </div>
                            </form>

                        </div>

                        {% for message in messages %}
                        <p id="messages">{{message}}</p>
                        {% endfor %}

                        <div class="mt-4">
                            <div class="d-flex justify-content-center links">
                                Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
                            </div>

                        </div>
                    </div>

                    .
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>



    <div class="circle" id="left"></div>
	<div class="circle" id="right"></div>
</body></html>

accounts/templates/accounts/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light bg">
  <a href="{% url 'home' %}">
    <img src="{% static 'images/singhealth-squarelogo.png' %}" width="70" style="margin-right: 10px;">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'announcements' %}">Announcements<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'reports' %}">Reports</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'stores' %}">Directory</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'chart' %}">Audit Statistics</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          For Auditor
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'send_email' %}">Send Email to a Tenant</a>
        </div>
      </li>
    </ul>

    <div class="dropdown" style="margin-left: 10px; padding-right: 15px;">
      <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Account
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href=""><b>{{ user.get_username }}</b></a>
        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        <!-- <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a> -->
      </div>
    </div>
  </div>
</nav>

accounts/templates/accounts/products.html
{% extends 'accounts/main.html' %}

{% block content %}
    <br>

        <div class="row">
            <div class="col-md">
                <div class="card card-body">
                    <h5>Products</h5>
                </div>
                <div class="card card-body">
                    <table class="table">
                        <tr>
                            <th>Product</th>
                            <th>Category</th>
                            <th>Price</th>
                        </tr>

                    </table>
                </div>
            </div>

        </div>

{% endblock %}

accounts/templates/accounts/rectify_form.html
{% extends 'accounts/main.html' %}
{% load static %}

{% block title %} - Rectify Form{% endblock title %}

{% block cssblock %}
<style>
    input{
        margin-right: 10px!important;
    }
    select{
        margin-left: 10px!important;
        max-width: 95vw!important;
    }


    #id_store {
        width: 10vw;
        margin-left: 55px!important;
    }

    #id_fbreport {
        width: 10vw;
        margin-left: 34px!important;
    }

    #id_nonfbreport {
        width: 10vw;
        margin-bottom: 30px;
    }

    #id_covid_compliance {
        width: 76vw;
    }
    #id_issue {
        margin-left: 89px!important;
        width: 76vw;
        margin-bottom: 30px;
    }
    #id_upload_image{
        margin-bottom: 30px;
    }

</style>
{% endblock cssblock %}

{% block content %}
<div style="margin: 0 0;">
    <div>
        <div style="margin: 20px 0px; color: #EA7C14">
            <h1>Submit Rectification</h1>
        </div>
    </div>
    <div style="padding-left: 10px;">
        <form action=" " enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" name="Submit">

        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/send_email.html
{% extends 'accounts/main.html' %}
{% load static %}

{% block title %} - Email{% endblock title %}

{% block cssblock %}
<style>
form li{
    list-style-type: none;
    color: #EA7C14;
    font-size: 0.8rem;
    margin-left: 40px;;
}
p{
    margin-bottom: 0!important;
    padding-bottom: 5px;
}
form ul{
    margin-bottom: 1px;
}
#id_email {
    margin-bottom: 10px;
    margin-left: 36px;
}
#id_subject {
    margin-bottom: 20px;
    margin-left: 24px;
}
#id_attach {
    margin-left: 29px;
    margin-bottom: 20px;
}
#id_message {
    margin-left: 15px;
    height: 100px;
    max-width: 90%;
}
p+input{
    margin-top: 40px;
}
</style>
{% endblock cssblock %}

{% block content %}
<div style="margin: 0 5%;">
    <div>
        <div style="margin: 20px 0px; color: #EA7C14">
            <h1>Send Email to Tenant</h1>
        </div>
    </div>
    <div style="padding-left: 10px;">
        <form action=" " enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" name="Submit">

        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/stats.html
<br>
<h5 style="padding-left: 15px;">Statistics:</h5>
<div class="row">
 <div class="col">
  <div class="col-md">
   <div class="card text-center text-white  mb-3" id="score">
      <div class="card-header">
       <h5 class="card-title">Audit Passing Score</h5>
      </div>
      <div class="card-body">
           <h5 class="card-title">95%</h5>
        <h3 class="card-title"></h3>
      </div>
   </div>
  </div>
 </div>

 <div class="col">
  <div class="col-md">
   <div class="card text-center text-white  mb-3" id="AuditDay">
      <div class="card-header">
       <h5 class="card-title">Next Audit Day</h5>
      </div>
      <div class="card-body">
        <h3 class="card-title"></h3>
      </tr>
      {% for store in stores %}
          <tr>
              <td>{{store.name}}</td>
              <td>{{store.audit_date}}</td>
          </tr>
      {% endfor %}
      </div>
   </div>
  </div>
 </div>

 <div class="col">
  <div class="col-md">
   <div class="card text-center text-white  mb-3" id="rectify">
      <div class="card-header">
       <h5 class="card-title">Total Rectifications Pending</h5>
      </div>
      <div class="card-body">
        <h3 class="card-title">{{pending}}</h3>
      </div>
   </div>
  </div>
 </div>
</div>

accounts/templates/accounts/stores.html
{% extends 'accounts/main.html' %}

{% block title %} - Stores{% endblock title %}

{% block content %}
    <br>

        <div class="row">
            <div class="col-md">
                <div class="card card-body">
                    <h5>Directory</h5>
                </div>
                <div class="card card-body">
                    <table class="table">
                        <tr>
                            <th>Store</th>
                            <th>Category</th>
                            <th>Description</th>
                        </tr>

                        {% for store in stores %}
							<tr>
								<td>{{store.name}}</td>
								<td>{{store.category}}</td>
								<td>{{store.description}}</td>
							</tr>
						{% endfor %}

                    </table>
                </div>
            </div>

        </div>

{% endblock %}

accounts/templates/accounts/webappName.html
{% load static %}
SingHealth WebApp